#! /usr/bin/env python

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

'''
Sends a message to Slack with a URL of the generated report of intermittents
and failures generated by `report.py` after upload in a Github Action step
'''

import argparse
import os
import sys

import requests


def parse_args(cmdln_args):
    parser = argparse.ArgumentParser(
        description='Performs post operations on dataset'
    )

    parser.add_argument(
        '--url',
        help='URL of report (HTML)',
        required=True
    )

    return parser.parse_args(args=cmdln_args)


def post_to_slack(data):
    webhook_url = os.environ.get('SLACK_WEBHOOK')

    print(data)
    try:
        requests.post(url=str(webhook_url), json=data, timeout=15)
    except requests.Timeout:
        pass
    except requests.ConnectionError:
        pass


def main():
    args = parse_args(sys.argv[1:])

    post_to_slack({
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "plain_text",
                    "text": f"HTML report generated: {args.url}"
                }
            }
        ]
    })


if __name__ == '__main__':
    main()
