name: "Daily UI Test (Intermittent/Failure) Report"

on:
  schedule:
    # Run every weekday (Mon-Fri) at 1:00 PM UTC
    - cron: 0 13 * * 1-5
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        configuration: [fenix, reference-browser, android-components, focus-android]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set current date as env variable
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y_%m_%d_%I_%M_%p')"
          echo "::set-output name=day::$(date +'%Y-%m-%d')"
      - name: Run script
        id: runClient
        run: |
          python treeherder-client.py --project=${{ matrix.configuration }}
          [ ! -e output.log ] || cat output.log
          [ ! -e output.json ] || cp output.json $JSON_FILE
          [ ! -e output.json ] || python post.py --input=output.json
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          JSON_FILE: ${{ steps.date.outputs.date }}_${{ matrix.configuration }}.json
      - uses: actions/upload-artifact@v2
        name: Upload Artifact (json)
        if: hashFiles('output.json') != ''
        with:
          name: JSON (${{ steps.date.outputs.date }}_${{ matrix.configuration }}.json) [zip]
          path: ${{ steps.date.outputs.date }}_${{ matrix.configuration }}.json
      - uses: google-github-actions/auth@v0
        name: Authenticate Google Cloud
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/upload-cloud-storage@v0
        if: hashFiles('output.json') != ''
        name: Upload Artifact (json) to Google Cloud Storage
        with: 
          path: ${{ steps.date.outputs.date }}_${{ matrix.configuration }}.json
          destination: mobile-reports/public/moz-mobile-test-health/${{ steps.date.outputs.day }}
      - name: Show public URL
        if: hashFiles('output.json') != ''
        run: |
          echo "Public URL: https://storage.googleapis.com/mobile-reports/public/moz-mobile-test-health/${{ steps.date.outputs.day }}/${{ steps.date.outputs.date }}_${{ matrix.configuration }}.json"
